// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnsihrjtrqjpczmqwfik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Induc2locmp0cnFqcGN6bXF3ZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjUzOTMsImV4cCI6MjA2NjM0MTM5M30.hAmVh19Cs42MleKvG722K5MqDFRbcOVfUUjME7kdiIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);